name: Deploy Lambda

on:
  push:
    branches:
    - develop
    paths:
    - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt -t ./package

      - name: Prepare deployment package
        run: |
          cp -r src/* package/
          cd package
          zip -r ../lambda_function.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
              --function-name prod-Acceptify-ReviewProcessor \
              --zip-file fileb://lambda_function.zip